language: go

go:
  - "1.10.x"

install:
  - go get -t ./...
  - make install-linters

script:
  - make check
  - make build-js-min

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify