sudo: required
dist: trusty
language: go

go:
  - "1.10.x"

install:
  - go get -t ./...
  - make install-linters
  - npm install --global source-map-support
  - go get github.com/gopherjs/gopherjs
  - cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/
  - npm install --global node-gyp
  - node-gyp rebuild
  - mkdir -p $HOME/.node_libraries/
  - cp build/Release/syscall.node $HOME/.node_libraries/syscall.node
  - cd -

script:
  - make check
  - make build-js-min
  - make test-js

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
